### ISSUE TITLE
Can't parse <label>

### ISSUE THREAD

**Issue by msmart** [dustin/py-github#39]
Maybe it's my mistake.

But gh.issues.list('repo','project') gives me in case of a private repository:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "github.py", line 104, in every
    return orig(self, *args)
  File "github.py", line 401, in list
    return self._parsed('/'.join(['issues', 'list', user, repo, state]))
  File "github.py", line 269, in _parsed
    return _parse(doc.documentElement)
  File "github.py", line 83, in _parse
    return _types[type](el)
  File "github.py", line 116, in _parseArray
    rv.append(_parse(ch))
  File "github.py", line 83, in _parse
    return _types[type](el)
  File "github.py", line 128, in __init__
    self.**dict**[ln] = _parse(ch)
  File "github.py", line 83, in _parse
    return _types[type](el)
  File "github.py", line 116, in _parseArray
    rv.append(_parse(ch))
  File "github.py", line 81, in _parse
    % (el.toxml(), repr(_types.keys())))
Exception: Can't parse <label>
        <name>improvement</name>
      </label>, known: ['committer', 'string', 'parent', 'float', 'datetime', 'boolean', 'plan', 'integer', 'array', 'network', 'author', 'repository', 'commit', 'public-key', 'issue']

**Comment by dustin** [comment]
I think this was fixed by 7240dc09
